# Generated by Django 5.1.2 on 2024-10-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='data',
        ),
        migrations.AddField(
            model_name='venda',
            name='data_venda',
            field=models.DateField(default='1970-01-01'),
        ),
        migrations.AddField(
            model_name='venda',
            name='preco',
            field=models.DecimalField(db_column='preço', decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venda',
            name='produto',
            field=models.CharField(default='Unknown Product', max_length=100),
        ),
        migrations.AddField(
            model_name='venda',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venda',
            name='regiao',
            field=models.CharField(default='Unknown Region', max_length=100),
        ),
        migrations.AddField(
            model_name='venda',
            name='vendedor',
            field=models.CharField(default='Unknown Seller', max_length=100),
        ),
        migrations.AlterField(
            model_name='venda',
            name='total_vendas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
